import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { parseStringPromise } from 'xml2js';
import { LiquidsoapConfig, LiquidsoapConfigSchema } from '@radio/shared';

const CONFIG_PATH =
  process.env.LIQUIDSOAP_CONFIG ||
  join(process.cwd(), '..', '..', 'liquidsoap', 'supervisor.json');

const SCRIPT_PATH =
  process.env.LIQUIDSOAP_SCRIPT ||
  join(process.cwd(), '..', '..', 'liquidsoap', 'mix-engine.liq');

const ICECAST_CONFIG_PATH =
  process.env.ICECAST_CONFIG ||
  join(process.cwd(), '..', '..', 'icecast', 'icecast.xml');

const DEFAULT_CONFIG: LiquidsoapConfig = LiquidsoapConfigSchema.parse({
  output: {},
  harbor: { password: 'changeme' },
  automation: {},
  crossfade: {},
});

export async function readLiquidsoapConfig(): Promise<LiquidsoapConfig> {
  try {
    const json = await readFile(CONFIG_PATH, 'utf-8');
    const parsed = JSON.parse(json);
    return LiquidsoapConfigSchema.parse(parsed);
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      return DEFAULT_CONFIG;
    }
    throw err;
  }
}

export async function writeLiquidsoapConfig(config: LiquidsoapConfig): Promise<void> {
  await writeFile(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  await generateRadioLiq(config);
}

async function readIcecastSourcePassword(): Promise<string> {
  const xml = await readFile(ICECAST_CONFIG_PATH, 'utf-8');
  const parsed = await parseStringPromise(xml, { trim: true });
  const password = parsed?.icecast?.authentication?.[0]?.['source-password']?.[0];
  if (!password) {
    throw new Error('Could not read source-password from icecast.xml');
  }
  return password;
}

export async function generateRadioLiq(config: LiquidsoapConfig): Promise<string> {
  const sourcePassword = await readIcecastSourcePassword();
  const script = renderScript(config, sourcePassword);
  await writeFile(SCRIPT_PATH, script, 'utf-8');
  return script;
}

function renderScript(config: LiquidsoapConfig, icecastSourcePassword: string): string {
  const lines: string[] = [];

  lines.push('# Generated by Radio app — DO NOT EDIT (use Settings → Mix Engine, or Raw Script for advanced).');
  lines.push('');
  lines.push('settings.server.telnet.set(true)');
  lines.push('settings.server.telnet.bind_addr.set("0.0.0.0")');
  lines.push('settings.server.telnet.port.set(1234)');
  lines.push('');

  lines.push('# Queue fed by the Supervisor over telnet (request.queue.push).');
  lines.push('# Empty queue plays silence; that is intentional and means "no Supervisor input yet".');
  lines.push('queue = request.queue(id="auto")');
  lines.push('');

  if (config.harbor.enabled) {
    lines.push('# Live source via Harbor (Icecast source-protocol input)');
    const args: string[] = [
      `id="live"`,
      `"${escapeStr(config.harbor.mount_name)}"`,
      `port=${config.harbor.port}`,
      `password="${escapeStr(config.harbor.password)}"`,
    ];
    if (config.harbor.tls.enabled && config.harbor.tls.certificate_path) {
      // Liquidsoap's input.harbor accepts transport=https.transport(...).
      // Cert path is mounted into the container at the same absolute path.
      args.push(
        `transport=https.transport(certificate="${escapeStr(config.harbor.tls.certificate_path)}", key="${escapeStr(config.harbor.tls.certificate_path)}")`,
      );
    }
    lines.push('live = input.harbor(');
    args.forEach((a, i) => lines.push(`  ${a}${i < args.length - 1 ? ',' : ''}`));
    lines.push(')');
    lines.push('');
  }

  lines.push('# Source priority — live takes over when present, queue otherwise');
  if (config.harbor.enabled && config.ducking.enabled) {
    // Liquidsoap 2.2 doesn't ship a top-level duck() operator. A real
    // implementation needs sidechain compression, which isn't a one-liner
    // and varies between LS versions. Until we wire that up, emit a
    // comment so the script still loads. The UI toggle remains so the
    // operator's intent is preserved when proper ducking lands.
    lines.push('# Ducking requested but not yet implemented in this LS version (TODO).');
    lines.push(`# Operator settings: depth=${config.ducking.depth_db} dB, attack=${config.ducking.attack_ms} ms, release=${config.ducking.release_ms} ms`);
  }
  // Adding blank() as the last fallback element guarantees the result
  // is infallible at the type level — LS 2.2's crossfade and other
  // downstream operators require this. mksafe(radio) wraps at runtime
  // but doesn't always propagate infallibility through the type
  // checker, so we put the safety in the fallback list itself.
  if (config.harbor.enabled) {
    lines.push('radio = fallback(track_sensitive=false, [live, queue, blank()])');
  } else {
    lines.push('radio = fallback(track_sensitive=false, [queue, blank()])');
  }
  if (config.crossfade.duration_seconds > 0) {
    // Liquidsoap 2.2's `cross` operator requires an explicit transition
    // function. `crossfade` is the higher-level wrapper with a default
    // linear fade built in — that's what we use for all three types here.
    // 'smart' enables Liquidsoap's auto-detection of fade points based
    // on track loudness. 'logarithmic' currently shares the same shape
    // as linear (the underlying fade.in/out functions accept a 'type'
    // argument that we'll wire up if/when an operator asks for it).
    const duration = config.crossfade.duration_seconds.toFixed(1);
    if (config.crossfade.type === 'smart') {
      lines.push(`radio = crossfade(smart=true, duration=${duration}, radio)`);
    } else {
      lines.push(`radio = crossfade(duration=${duration}, radio)`);
    }
  }
  lines.push('');

  if (config.master_bus.soft_limiter) {
    lines.push('# Master bus: soft limiter at -1 dBFS (high-ratio compressor, only engages on transients)');
    lines.push('radio = compress(threshold=-1.0, ratio=20.0, attack=5.0, release=50.0, radio)');
  }

  lines.push('# Output to Icecast (source password resolved from icecast.xml at generation time)');
  lines.push('output.icecast(');
  lines.push(`  ${formatCodec(config.output.codec, config.output.bitrate_kbps)},`);
  lines.push(`  host="${escapeStr(config.output.icecast_host)}",`);
  lines.push(`  port=${config.output.icecast_port},`);
  lines.push('  user="source",');
  lines.push(`  password="${escapeStr(icecastSourcePassword)}",`);
  lines.push(`  mount="${escapeStr(config.output.icecast_mount)}",`);
  lines.push('  radio');
  lines.push(')');
  lines.push('');

  return lines.join('\n');
}

function formatCodec(codec: string, bitrate: number): string {
  switch (codec) {
    case 'mp3':
      return `%mp3(bitrate=${bitrate}, samplerate=44100, stereo=true)`;
    case 'aac':
      return `%fdkaac(bitrate=${bitrate}, samplerate=44100, channels=2)`;
    case 'opus':
      return `%opus(bitrate=${bitrate}, samplerate=48000, channels=2, application="audio")`;
    case 'vorbis':
      return `%vorbis(quality=0.5, samplerate=44100, channels=2)`;
    default:
      return `%mp3(bitrate=${bitrate}, samplerate=44100, stereo=true)`;
  }
}

function escapeStr(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export async function readRadioLiq(): Promise<string> {
  return readFile(SCRIPT_PATH, 'utf-8');
}

export async function writeRadioLiq(content: string): Promise<void> {
  await writeFile(SCRIPT_PATH, content, 'utf-8');
}
