import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { parseStringPromise } from 'xml2js';
import { LiquidsoapConfig, LiquidsoapConfigSchema } from '@soono/shared';

const CONFIG_PATH =
  process.env.LIQUIDSOAP_CONFIG ||
  join(process.cwd(), '..', '..', 'liquidsoap', 'supervisor.json');

const SCRIPT_PATH =
  process.env.LIQUIDSOAP_SCRIPT ||
  join(process.cwd(), '..', '..', 'liquidsoap', 'mix-engine.liq');

const ICECAST_CONFIG_PATH =
  process.env.ICECAST_CONFIG ||
  join(process.cwd(), '..', '..', 'icecast', 'icecast.xml');

const DEFAULT_CONFIG: LiquidsoapConfig = LiquidsoapConfigSchema.parse({
  output: {},
  harbor: { password: 'changeme' },
  automation: {},
  crossfade: {},
});

export async function readLiquidsoapConfig(): Promise<LiquidsoapConfig> {
  try {
    const json = await readFile(CONFIG_PATH, 'utf-8');
    const parsed = JSON.parse(json);
    return LiquidsoapConfigSchema.parse(parsed);
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      return DEFAULT_CONFIG;
    }
    throw err;
  }
}

export async function writeLiquidsoapConfig(config: LiquidsoapConfig): Promise<void> {
  await writeFile(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  await generateRadioLiq(config);
}

async function readIcecastSourcePassword(): Promise<string> {
  const xml = await readFile(ICECAST_CONFIG_PATH, 'utf-8');
  const parsed = await parseStringPromise(xml, { trim: true });
  const password = parsed?.icecast?.authentication?.[0]?.['source-password']?.[0];
  if (!password) {
    throw new Error('Could not read source-password from icecast.xml');
  }
  return password;
}

export async function generateRadioLiq(config: LiquidsoapConfig): Promise<string> {
  const sourcePassword = await readIcecastSourcePassword();
  const script = renderScript(config, sourcePassword);
  await writeFile(SCRIPT_PATH, script, 'utf-8');
  return script;
}

function renderScript(config: LiquidsoapConfig, icecastSourcePassword: string): string {
  const lines: string[] = [];
  const apiUrl = process.env.LS_API_URL ?? 'http://host.docker.internal:3000';

  lines.push('# Generated by Soono — DO NOT EDIT (use Settings → Mix Engine, or Raw Script for advanced).');
  lines.push('');
  lines.push('settings.server.telnet.set(true)');
  lines.push('settings.server.telnet.bind_addr.set("0.0.0.0")');
  lines.push('settings.server.telnet.port.set(1234)');
  lines.push('');
  lines.push('# Queue fed by the Supervisor over HTTP harbor (POST /push).');
  lines.push('# Empty queue plays silence; that is intentional and means "no Supervisor input yet".');
  lines.push('queue = request.queue(id="auto")');
  lines.push('');

  if (config.harbor.enabled) {
    lines.push('# Live source via Harbor (Icecast source-protocol input).');
    lines.push('# The control HTTP endpoints below share this same port — harbor multiplexes by path.');
    const args: string[] = [
      `id="live"`,
      `"${escapeStr(config.harbor.mount_name)}"`,
      `port=${config.harbor.port}`,
      `password="${escapeStr(config.harbor.password)}"`,
    ];
    if (config.harbor.tls.enabled && config.harbor.tls.certificate_path) {
      // Cert path is mounted into the container at the same absolute path.
      args.push(
        `transport=https.transport(certificate="${escapeStr(config.harbor.tls.certificate_path)}", key="${escapeStr(config.harbor.tls.certificate_path)}")`,
      );
    }
    lines.push('live = input.harbor(');
    args.forEach((a, i) => lines.push(`  ${a}${i < args.length - 1 ? ',' : ''}`));
    lines.push(')');
    lines.push('');

    lines.push('# ── Supervisor V2 — Harbor HTTP control endpoints ────────────────────────────');
    lines.push('#');
    lines.push('# POST /push   — push an annotated URI onto the queue; returns {ok, request_id}');
    lines.push('# GET  /queue  — return current queue depth and request IDs');
    lines.push('# POST /skip   — skip the currently playing track');
    lines.push('# GET  /live-status — return whether the live harbor input is connected');
    lines.push('#');
    lines.push('# All handlers run inside the LS audio thread; outbound HTTP (webhooks) MUST');
    lines.push('# use thread.run to avoid blocking the audio pipeline.');
    lines.push('');

    // LS 2.2: path is positional (not uri=), handler is fun (req, res),
    // body is req.body() (getter), response via res.json()/res.status_code().
    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="POST",`);
    lines.push(`  "/push",`);
    lines.push(`  fun (req, res) ->`);
    lines.push(`    begin`);
    lines.push(`      body = req.body()`);
    lines.push(`      parsed = json.parse(default={uri = ""}, body)`);
    lines.push(`      ann_uri = parsed.uri`);
    lines.push(`      if ann_uri == "" then`);
    lines.push(`        res.status_code(400)`);
    lines.push(`        res.json({ok = false, error = "uri is required"})`);
    lines.push(`      else`);
    lines.push(`        r = request.create(ann_uri)`);
    lines.push(`        queue.push(r)`);
    lines.push(`        rid = "#{request.id(r)}"`);
    lines.push(`        res.json({ok = true, request_id = rid})`);
    lines.push(`      end`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');

    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="GET",`);
    lines.push(`  "/queue",`);
    lines.push(`  fun (_req, res) ->`);
    lines.push(`    begin`);
    lines.push(`      ids = list.map(fun (r) -> "#{request.id(r)}", queue.queue())`);
    lines.push(`      depth = list.length(ids)`);
    lines.push(`      res.json({depth = depth, ids = ids})`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');

    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="POST",`);
    lines.push(`  "/skip",`);
    lines.push(`  fun (_req, res) ->`);
    lines.push(`    begin`);
    lines.push(`      queue.skip()`);
    lines.push(`      res.json({ok = true})`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');

    // LS 2.2: live.is_connected() was removed; use null.defined(live.connected_client()).
    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="GET",`);
    lines.push(`  "/live-status",`);
    lines.push(`  fun (_req, res) ->`);
    lines.push(`    begin`);
    lines.push(`      connected = null.defined(live.connected_client())`);
    lines.push(`      res.json({connected = connected})`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');

    lines.push('# ── Supervisor V2 — Webhooks to API ─────────────────────────────────────────');
    lines.push('#');
    lines.push('# on_track fires when LS transitions to a new audio item.');
    lines.push('# on_end fires N seconds before the current track ends.');
    lines.push('#');
    lines.push('# Both must use thread.run — HTTP calls in the audio thread cause dropouts.');
    lines.push('');
    lines.push(`let api_url = "${escapeStr(apiUrl)}"`);
    lines.push('');

    lines.push('queue.on_track(fun (meta) ->');
    lines.push('  thread.run(fun () ->');
    lines.push('    begin');
    lines.push('      uri = list.assoc(default="", "filename", meta)');
    lines.push('      phid = list.assoc(default="", "play_history_id", meta)');
    lines.push('      payload = json.stringify({');
    lines.push('        uri = uri,');
    lines.push('        on_air_timestamp = time(),');
    lines.push('        play_history_id = phid');
    lines.push('      })');
    lines.push('      ignore(http.post(');
    lines.push('        headers=[("Content-Type", "application/json")],');
    lines.push('        data=payload,');
    lines.push('        "#{api_url}/internal/ls/track-started"');
    lines.push('      ))');
    lines.push('    end');
    lines.push('  )');
    lines.push(')');
    lines.push('');

    // LS 2.2: on_end signature is on_end(delay, source, handler) — source before handler.
    lines.push('on_end(');
    lines.push('  delay=5.,');
    lines.push('  queue,');
    lines.push('  fun (remaining, meta) ->');
    lines.push('    thread.run(fun () ->');
    lines.push('      begin');
    lines.push('        uri = list.assoc(default="", "filename", meta)');
    lines.push('        phid = list.assoc(default="", "play_history_id", meta)');
    lines.push('        payload = json.stringify({');
    lines.push('          uri = uri,');
    lines.push('          remaining_seconds = remaining,');
    lines.push('          play_history_id = phid');
    lines.push('        })');
    lines.push('        ignore(http.post(');
    lines.push('          headers=[("Content-Type", "application/json")],');
    lines.push('          data=payload,');
    lines.push('          "#{api_url}/internal/ls/track-ending"');
    lines.push('        ))');
    lines.push('      end');
    lines.push('    )');
    lines.push(')');
    lines.push('');
  }

  lines.push('# Source priority — live takes over when present, queue otherwise');
  if (config.harbor.enabled && config.ducking.enabled) {
    // LS 2.2 has no top-level duck() operator; emit a comment so the script
    // still loads. The UI toggle preserves the operator's intent for when
    // proper sidechain ducking is wired up.
    lines.push('# Ducking requested but not yet implemented in this LS version (TODO).');
    lines.push(`# Operator settings: depth=${config.ducking.depth_db} dB, attack=${config.ducking.attack_ms} ms, release=${config.ducking.release_ms} ms`);
  }
  if (config.harbor.enabled) {
    lines.push('radio = fallback(track_sensitive=false, [live, queue, blank()])');
  } else {
    lines.push('radio = fallback(track_sensitive=false, [queue, blank()])');
  }
  if (config.crossfade.duration_seconds > 0) {
    // LS 2.2 crossfade requires an infallible source; fallback() returns
    // source(?'a) so crossfade rejects it. Skipping until a working pattern
    // is found with a live LS 2.2 interpreter.
    lines.push(
      `# Crossfade requested (${config.crossfade.duration_seconds}s ${config.crossfade.type}) but skipped — LS 2.2's crossfade rejects fallible sources. TODO.`,
    );
  }
  lines.push('');

  if (config.master_bus.soft_limiter) {
    lines.push('# Master bus: soft limiter at -1 dBFS (high-ratio compressor, only engages on transients)');
    lines.push('radio = compress(threshold=-1.0, ratio=20.0, attack=5.0, release=50.0, radio)');
  }

  lines.push('# Output to Icecast (source password resolved from icecast.xml at generation time)');
  lines.push('output.icecast(');
  lines.push(`  ${formatCodec(config.output.codec, config.output.bitrate_kbps)},`);
  lines.push(`  host="${escapeStr(config.output.icecast_host)}",`);
  lines.push(`  port=${config.output.icecast_port},`);
  lines.push('  user="source",');
  lines.push(`  password="${escapeStr(icecastSourcePassword)}",`);
  lines.push(`  mount="${escapeStr(config.output.icecast_mount)}",`);
  lines.push('  radio');
  lines.push(')');
  lines.push('');

  return lines.join('\n');
}

function formatCodec(codec: string, bitrate: number): string {
  switch (codec) {
    case 'mp3':
      return `%mp3(bitrate=${bitrate}, samplerate=44100, stereo=true)`;
    case 'aac':
      return `%fdkaac(bitrate=${bitrate}, samplerate=44100, channels=2)`;
    case 'opus':
      return `%opus(bitrate=${bitrate}, samplerate=48000, channels=2, application="audio")`;
    case 'vorbis':
      return `%vorbis(quality=0.5, samplerate=44100, channels=2)`;
    default:
      return `%mp3(bitrate=${bitrate}, samplerate=44100, stereo=true)`;
  }
}

function escapeStr(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export async function readRadioLiq(): Promise<string> {
  return readFile(SCRIPT_PATH, 'utf-8');
}

export async function writeRadioLiq(content: string): Promise<void> {
  await writeFile(SCRIPT_PATH, content, 'utf-8');
}
