import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { parseStringPromise } from 'xml2js';
import { LiquidsoapConfig, LiquidsoapConfigSchema } from '@radio/shared';

const CONFIG_PATH =
  process.env.LIQUIDSOAP_CONFIG ||
  join(process.cwd(), '..', '..', 'liquidsoap', 'supervisor.json');

const SCRIPT_PATH =
  process.env.LIQUIDSOAP_SCRIPT ||
  join(process.cwd(), '..', '..', 'liquidsoap', 'mix-engine.liq');

const ICECAST_CONFIG_PATH =
  process.env.ICECAST_CONFIG ||
  join(process.cwd(), '..', '..', 'icecast', 'icecast.xml');

const DEFAULT_CONFIG: LiquidsoapConfig = LiquidsoapConfigSchema.parse({
  output: {},
  harbor: { password: 'changeme' },
  automation: {},
  crossfade: {},
});

export async function readLiquidsoapConfig(): Promise<LiquidsoapConfig> {
  try {
    const json = await readFile(CONFIG_PATH, 'utf-8');
    const parsed = JSON.parse(json);
    return LiquidsoapConfigSchema.parse(parsed);
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      return DEFAULT_CONFIG;
    }
    throw err;
  }
}

export async function writeLiquidsoapConfig(config: LiquidsoapConfig): Promise<void> {
  await writeFile(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  await generateRadioLiq(config);
}

async function readIcecastSourcePassword(): Promise<string> {
  const xml = await readFile(ICECAST_CONFIG_PATH, 'utf-8');
  const parsed = await parseStringPromise(xml, { trim: true });
  const password = parsed?.icecast?.authentication?.[0]?.['source-password']?.[0];
  if (!password) {
    throw new Error('Could not read source-password from icecast.xml');
  }
  return password;
}

export async function generateRadioLiq(config: LiquidsoapConfig): Promise<string> {
  const sourcePassword = await readIcecastSourcePassword();
  const script = renderScript(config, sourcePassword);
  await writeFile(SCRIPT_PATH, script, 'utf-8');
  return script;
}

function renderScript(config: LiquidsoapConfig, icecastSourcePassword: string): string {
  const lines: string[] = [];

  lines.push('# Generated by Radio app — DO NOT EDIT (use Settings → Mix Engine, or Raw Script for advanced).');
  lines.push('');
  lines.push('# Queue fed by the Supervisor over HTTP harbor (POST /push).');
  lines.push('# Empty queue plays silence; that is intentional and means "no Supervisor input yet".');
  lines.push('queue = request.queue(id="auto")');
  lines.push('');

  if (config.harbor.enabled) {
    lines.push('# Live source via Harbor (Icecast source-protocol input).');
    lines.push('# The control HTTP endpoints below share this same port — harbor multiplexes by path.');
    const args: string[] = [
      `id="live"`,
      `"${escapeStr(config.harbor.mount_name)}"`,
      `port=${config.harbor.port}`,
      `password="${escapeStr(config.harbor.password)}"`,
    ];
    if (config.harbor.tls.enabled && config.harbor.tls.certificate_path) {
      // Liquidsoap's input.harbor accepts transport=https.transport(...).
      // Cert path is mounted into the container at the same absolute path.
      args.push(
        `transport=https.transport(certificate="${escapeStr(config.harbor.tls.certificate_path)}", key="${escapeStr(config.harbor.tls.certificate_path)}")`,
      );
    }
    lines.push('live = input.harbor(');
    args.forEach((a, i) => lines.push(`  ${a}${i < args.length - 1 ? ',' : ''}`));
    lines.push(')');
    lines.push('');

    lines.push('# ── Supervisor V2 — Harbor HTTP control endpoints ────────────────────────────');
    lines.push('');
    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="POST",`);
    lines.push(`  uri="/push",`);
    lines.push(`  fun (req) ->`);
    lines.push(`    begin`);
    lines.push(`      parsed = json.parse(default={"uri": ""}, req.body)`);
    lines.push(`      uri = parsed.uri`);
    lines.push(`      if uri == "" then`);
    lines.push(`        {status_code = 400, headers = [("Content-Type", "application/json")], body = json.stringify({ok = false, error = "uri is required"})}`);
    lines.push(`      else`);
    lines.push(`        r = request.create(uri)`);
    lines.push(`        queue.push(r)`);
    lines.push(`        rid = string_of(request.id(r))`);
    lines.push(`        {status_code = 200, headers = [("Content-Type", "application/json")], body = json.stringify({ok = true, request_id = rid})}`);
    lines.push(`      end`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');
    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="GET",`);
    lines.push(`  uri="/queue",`);
    lines.push(`  fun (_req) ->`);
    lines.push(`    begin`);
    lines.push(`      ids = list.map(fun (r) -> string_of(request.id(r)), queue.queue())`);
    lines.push(`      depth = list.length(ids)`);
    lines.push(`      {status_code = 200, headers = [("Content-Type", "application/json")], body = json.stringify({depth = depth, ids = ids})}`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');
    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="POST",`);
    lines.push(`  uri="/skip",`);
    lines.push(`  fun (_req) ->`);
    lines.push(`    begin`);
    lines.push(`      queue.skip()`);
    lines.push(`      {status_code = 200, headers = [("Content-Type", "application/json")], body = json.stringify({ok = true})}`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');
    lines.push(`harbor.http.register(`);
    lines.push(`  port=${config.harbor.port},`);
    lines.push(`  method="GET",`);
    lines.push(`  uri="/live-status",`);
    lines.push(`  fun (_req) ->`);
    lines.push(`    begin`);
    lines.push(`      connected = live.is_connected()`);
    lines.push(`      {status_code = 200, headers = [("Content-Type", "application/json")], body = json.stringify({connected = connected})}`);
    lines.push(`    end`);
    lines.push(`)`);
    lines.push('');
    lines.push('# ── Supervisor V2 — Webhooks to API ─────────────────────────────────────────');
    lines.push('# All outbound HTTP calls are wrapped in thread.run to avoid audio dropouts.');
    lines.push('');
    lines.push('let api_url = "http://host.docker.internal:3000"');
    lines.push('');
    lines.push('queue.on_track(fun (meta) ->');
    lines.push('  thread.run(fun () ->');
    lines.push('    begin');
    lines.push('      uri = list.assoc(default="", "filename", meta)');
    lines.push('      on_air_ts = list.assoc(default="0.0", "on_air_timestamp", meta)');
    lines.push('      phid = list.assoc(default="", "play_history_id", meta)');
    lines.push('      payload = json.stringify({');
    lines.push('        uri = uri,');
    lines.push('        on_air_timestamp = float_of_string(default=0.0, on_air_ts),');
    lines.push('        play_history_id = phid');
    lines.push('      })');
    lines.push('      ignore(http.post(');
    lines.push('        headers=[("Content-Type", "application/json")],');
    lines.push('        data=payload,');
    lines.push('        "#{api_url}/internal/ls/track-started"');
    lines.push('      ))');
    lines.push('    end');
    lines.push('  )');
    lines.push(')');
    lines.push('');
    lines.push('on_end(');
    lines.push('  delay=5.,');
    lines.push('  fun (remaining, meta) ->');
    lines.push('    thread.run(fun () ->');
    lines.push('      begin');
    lines.push('        uri = list.assoc(default="", "filename", meta)');
    lines.push('        phid = list.assoc(default="", "play_history_id", meta)');
    lines.push('        payload = json.stringify({');
    lines.push('          uri = uri,');
    lines.push('          remaining_seconds = remaining,');
    lines.push('          play_history_id = phid');
    lines.push('        })');
    lines.push('        ignore(http.post(');
    lines.push('          headers=[("Content-Type", "application/json")],');
    lines.push('          data=payload,');
    lines.push('          "#{api_url}/internal/ls/track-ending"');
    lines.push('        ))');
    lines.push('      end');
    lines.push('    ),');
    lines.push('  queue');
    lines.push(')');
    lines.push('');
  }

  lines.push('# Source priority — live takes over when present, queue otherwise');
  if (config.harbor.enabled && config.ducking.enabled) {
    // Liquidsoap 2.2 doesn't ship a top-level duck() operator. A real
    // implementation needs sidechain compression, which isn't a one-liner
    // and varies between LS versions. Until we wire that up, emit a
    // comment so the script still loads. The UI toggle remains so the
    // operator's intent is preserved when proper ducking lands.
    lines.push('# Ducking requested but not yet implemented in this LS version (TODO).');
    lines.push(`# Operator settings: depth=${config.ducking.depth_db} dB, attack=${config.ducking.attack_ms} ms, release=${config.ducking.release_ms} ms`);
  }
  // blank() at the tail keeps the runtime always-on. Type-wise LS 2.2
  // still treats fallback as source(?'a), but the output operator
  // accepts fallible sources, so this is fine for the simple chain.
  if (config.harbor.enabled) {
    lines.push('radio = fallback(track_sensitive=false, [live, queue, blank()])');
  } else {
    lines.push('radio = fallback(track_sensitive=false, [queue, blank()])');
  }
  if (config.crossfade.duration_seconds > 0) {
    // Crossfade in LS 2.2 requires source('a) (infallible at the type
    // level), and fallback(...) returns source(?'a) regardless of
    // children. mksafe() is just sugar for fallback-with-blank and has
    // the same type. The realistic 2.2 idiom is "apply crossfade to a
    // playlist() (infallible), then fallback with harbor", which our
    // request.queue-based shape doesn't match. Skipping crossfade for
    // now; tracks will hard-cut between songs. TODO: revisit with a
    // live LS 2.2 interpreter to find a pattern that works.
    lines.push(
      `# Crossfade requested (${config.crossfade.duration_seconds}s ${config.crossfade.type}) but skipped — LS 2.2's crossfade rejects fallible sources. TODO.`,
    );
  }
  lines.push('');

  if (config.master_bus.soft_limiter) {
    lines.push('# Master bus: soft limiter at -1 dBFS (high-ratio compressor, only engages on transients)');
    lines.push('radio = compress(threshold=-1.0, ratio=20.0, attack=5.0, release=50.0, radio)');
  }

  lines.push('# Output to Icecast (source password resolved from icecast.xml at generation time)');
  lines.push('output.icecast(');
  lines.push(`  ${formatCodec(config.output.codec, config.output.bitrate_kbps)},`);
  lines.push(`  host="${escapeStr(config.output.icecast_host)}",`);
  lines.push(`  port=${config.output.icecast_port},`);
  lines.push('  user="source",');
  lines.push(`  password="${escapeStr(icecastSourcePassword)}",`);
  lines.push(`  mount="${escapeStr(config.output.icecast_mount)}",`);
  lines.push('  radio');
  lines.push(')');
  lines.push('');

  return lines.join('\n');
}

function formatCodec(codec: string, bitrate: number): string {
  switch (codec) {
    case 'mp3':
      return `%mp3(bitrate=${bitrate}, samplerate=44100, stereo=true)`;
    case 'aac':
      return `%fdkaac(bitrate=${bitrate}, samplerate=44100, channels=2)`;
    case 'opus':
      return `%opus(bitrate=${bitrate}, samplerate=48000, channels=2, application="audio")`;
    case 'vorbis':
      return `%vorbis(quality=0.5, samplerate=44100, channels=2)`;
    default:
      return `%mp3(bitrate=${bitrate}, samplerate=44100, stereo=true)`;
  }
}

function escapeStr(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export async function readRadioLiq(): Promise<string> {
  return readFile(SCRIPT_PATH, 'utf-8');
}

export async function writeRadioLiq(content: string): Promise<void> {
  await writeFile(SCRIPT_PATH, content, 'utf-8');
}
